[package]
name = "quicksort_gen"
version = "0.1.0"
edition = "2018"
description = "Generic implementation of quicksort algorithm"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
